### ISSUE TITLE
matrix.php

### ISSUE THREAD

**Issue by Dolphin83** [grizzzli74/test_dornet#2]
1. Не считает сумму по столбцам. Только по строкам.
![image](https://github.com/grizzzli74/test_dornet/assets/1169704/3be99779-061a-4ad8-8d79-21a1081ba3c9)

2. При конфигрурации 
$n = 5;
$m = 5;
$q = 9;
Выводит только одну строку, хотя возможные значения для заполнения матрицы еще есть.
![image](https://github.com/grizzzli74/test_dornet/assets/1169704/feaef84a-27ea-459d-9a9f-abe477f13dbb)

**Comment by grizzzli74** [comment]
Пофиксил.
[Ветка](https://github.com/grizzzli74/test_dornet/tree/fix-matrix)
Добавил дополнительное решение через регулярку.
