### ISSUE TITLE
sum.php

### ISSUE THREAD

**Issue by Dolphin83** [grizzzli74/test_dornet#3]
Это не совсем то, что требовалось.
Давай усложним задачу и внесем новое требование, что приведение типов использоваться нельзя.
Решением должно корректно выводить  сумму двух чисел с длиной строки ~100 символов.

Например такие:

$a = '111111111111111111111111111111111111111111111111111111111111111111111111222222222222222222222222222222234324234234324324';
$b = '131313131313131313131313131313131313131313131313131313131313131313131313123123123123123123123123123123234234234234234234';

**Comment by grizzzli74** [comment]
Пофиксил.
Ветка https://github.com/grizzzli74/test_dornet/tree/fix-sum 
Добавил дополнительное решение через регулярку.
